import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {inspectExtensionRevision} from '@jimhoyd/urlcode/extensions';
import {createAuthService,AuthHttp} from '@jimhoyd/urlcode-auth';
import {createAdministrationRuntime} from '../src/admin-runtime.ts';
test('administration runtime wires live health and decorates cached application responses during support sessions',async t=>{
 const root=await mkdtemp(join(tmpdir(),'admin-runtime-')),project=join(root,'app');await mkdir(project);t.after(()=>rm(root,{recursive:true,force:true}));
 await writeFile(join(project,'urlcode.yaml'),JSON.stringify({version:'1',extensions:{auth:{version:'1',config:{registration:'open'}},admin:{version:'1',config:{}}},routes:{'/account/*':{extension:'auth',methods:['GET','HEAD','POST']},'/admin/*':{extension:'admin',methods:['GET','HEAD','POST']},'/app':{respond:{text:'<html><body><h1>Application</h1></body></html>'},response:{headers:{'content-type':'text/html'}},policies:{cache:{strategy:'public',maxAge:60}}}}}));
 const service=await createAuthService({database:join(root,'auth.sqlite'),encryptionKey:randomBytes(32),roles:{member:[],admin:['*']},defaultRole:'member',allowImpersonation:true});t.after(()=>service.close());
 const password='synthetic runtime integration passphrase',owner=await service.bootstrapAdmin({email:'owner@example.test',password}),member=await service.register({email:'member@example.test',password});
 const origin='https://runtime.example',csrfKey=randomBytes(32),projectSha256=await inspectExtensionRevision(project);let notices=0;
 const runtime=await createAdministrationRuntime(project,{auth:{service,csrfKey,projectSha256},admin:{notifyImpersonation:async()=>{notices++;}},runtime:{origin},observations:async()=>({sender:'degraded',providers:[{id:'example',status:'unknown'}],alerts:['sender-failed']})});t.after(()=>runtime.close());
 const normal=await runtime.handle({target:'/app'});assert.doesNotMatch(Buffer.from(normal.body!).toString(),/urlcode-support-banner/);
 const ownerHeaders=new Headers({cookie:'__Host-urlcode-session='+owner.token,accept:'application/json'});
 const health=await runtime.handle({target:'/admin/health',headers:ownerHeaders});assert.equal(health.status,200);const observed=JSON.parse(Buffer.from(health.body!).toString());assert.match(JSON.stringify(observed),/"sender":"degraded"/);assert.match(JSON.stringify(observed),new RegExp('"routes":'+runtime.count));
 const headers=new Headers(ownerHeaders);headers.set('origin',origin);headers.set('content-type','application/json');
 const started=await runtime.handle({target:'/admin/impersonate',method:'POST',headers,body:Buffer.from(JSON.stringify({csrf:new AuthHttp({origin,csrfKey}).token(owner.token),accountId:member.user.id,reason:'Synthetic support integration review'}))});assert.equal(started.status,303);assert.equal(notices,1);
 const cookie=started.headers.find(([key,value])=>key==='set-cookie'&&value.startsWith('__Host-urlcode-session='))![1].split(';')[0]!;
 const supportHeaders=new Headers({cookie,'if-none-match':'previous','accept-encoding':'gzip',accept:'application/json'});
 const page=await runtime.handle({target:'/app',headers:supportHeaders});assert.equal(page.status,200);assert.match(Buffer.from(page.body!).toString(),/<body><aside role="alert"/);assert.ok(page.headers.some(([key,value])=>key==='cache-control'&&value==='no-store'));assert.ok(!page.headers.some(([key])=>key==='etag'));
 assert.equal((await runtime.handle({target:'/admin',headers:supportHeaders})).status,404);
 const raw=cookie.slice(cookie.indexOf('=')+1);await service.logout(raw);
 const after=await runtime.handle({target:'/app',headers:supportHeaders});assert.doesNotMatch(Buffer.from(after.body!).toString(),/urlcode-support-banner/);
 assert.ok(await service.authenticate(owner.token));
});
