import {escapeHtml,icon,hiddenField,postForm} from '@jimhoyd/urlcode-ui';
import {csrfField,formField,hasPermission} from '@jimhoyd/urlcode-auth';
import type {AuthPrincipal,AuthUser,PresentationContext} from '@jimhoyd/urlcode-auth';
import {nextPage,observedLastSeen,userFilterFields,userFilterKeys} from './admin-reporting.ts';
import {markup} from './admin-ui.ts';
import type {Screen} from './admin-ui.ts';

/** Account workflows and authority stay here; URLCode UI supplies only generic visual primitives. */
export function userDirectory(input:{users:AuthUser[];next?:string;query:URLSearchParams;principal:AuthPrincipal;mount:string;csrf:string;presentation:PresentationContext;canSendSetup:boolean}):Screen {
 const {users,query,principal,mount,csrf,presentation}=input;
 const text=(source:string)=>presentation.textSource(source),html=(source:string)=>escapeHtml(text(source));
 const tr=(key:string,values?:Record<string,string|number>)=>presentation.text(key,values),trh=(key:string,values?:Record<string,string|number>)=>escapeHtml(tr(key,values));
 const field=(name:string,label:string,type='text')=>formField(name,text(label),type);
 const form=(path:string,fields:string,label:string,destructive=false)=>postForm({action:mount+path,csrf,fields,label:text(label),destructive,className:'ui-form-grid'});
 const manage=hasPermission(principal,'auth.users.manage'),sessions=hasPermission(principal,'auth.sessions.manage'),select=manage||sessions;
 const setup=input.canSendSetup&&hasPermission(principal,'auth.users.create')?{summary:text('Create account and send setup link'),form:markup(form('/users/create',field('email','Email address','email')+field('reason','Reason'),'Create account and send setup link'))}:null;
 const filters=`<form method="get" action="${escapeHtml(mount+'/users')}">${userFilterFields(query,text)}<div class="ui-toolbar"><button type="submit">${icon('search')}<span>${trh('users.filter.apply')}</span></button><a href="${escapeHtml(mount+'/users'+(query.get('lang')?'?lang='+encodeURIComponent(query.get('lang')!):''))}">${html('Reset filters')}</a></div></form>`;
 const exports=hasPermission(principal,'auth.users.export')?{summary:markup(icon('download')+`<span>${html('Export accounts')}</span>`),forms:markup(form('/users/export-page',[...userFilterKeys,'after'].map(key=>hiddenField(key,query.get(key)||'')).join('')+field('reason','Reason')+`<p class="ui-muted">${trh('copy.exportThisFilteredPageOnlyAtMost50AccountsEmailAddressesStayMasked')}</p>`,'Export this page as CSV')+form('/users/export-range',userFilterKeys.map(key=>hiddenField(key,query.get(key)||'')).join('')+field('reason','Reason')+`<p class="ui-muted">${html('Complete export: at most 5,000 accounts, 4 MiB and 5 seconds. Narrow filters if the limit is exceeded.')}</p>`,'Export all matching accounts as CSV'))}:null;
 const bulk=select?{summary:tr('copy.bulkAction'),form:markup(`<form class="ui-form-grid" id="bulk-users" method="post" action="${escapeHtml(mount+'/users/bulk')}">${csrfField(csrf)}<label>${trh('copy.bulkAction')}<select name="action">${manage?`<option value="lock">${trh('copy.lock')}</option><option value="unlock">${trh('copy.unlock')}</option>`:''}${sessions?`<option value="revoke-sessions">${trh('action.revokeSessions')}</option>`:''}</select></label>${field('reason','Reason')}${field('confirmation','Type LOCK, UNLOCK or REVOKE-SESSIONS followed by a space and the selected count')}<p class="ui-muted">${trh('copy.selectAccountsInTheTableAllSelectedAccountsMustBePermittedOtherwiseNoneAreChanged')}</p><button class="ui-button-destructive" type="submit">${trh('copy.applyBulkAction')}</button></form>`)}:null;
 const rows=users.map(user=>`<tr><td>${user.id!==principal.id&&user.status!=='pending-delete'&&select?`<input type="checkbox" form="bulk-users" name="selected.${escapeHtml(user.id)}" value="yes" aria-label="${trh('action.selectAccount',{account:user.email})}">`:''}</td><td><a href="${escapeHtml(mount+'/users/detail?id='+encodeURIComponent(user.id))}"><strong>${escapeHtml(user.email)}</strong></a><small class="ui-muted ui-account-id">${escapeHtml(user.id)}</small></td><td><span class="ui-badge" data-status="${escapeHtml(user.status)}">${html(user.status)}</span></td><td class="ui-muted">${observedLastSeen(user)?`<time datetime="${escapeHtml(observedLastSeen(user))}">${escapeHtml(observedLastSeen(user).replace('T',' ').slice(0,16)+' UTC')}</time>`:'—'}</td><td>${user.roles.map(role=>`<span class="ui-badge">${escapeHtml(role)}</span>`).join(' ')}</td><td>${manage&&user.id!==principal.id&&user.status!=='pending-delete'?`<details><summary>${html(user.status==='active'?'Lock account':'Unlock account')}</summary>${form('/users/status',hiddenField('accountId',user.id)+hiddenField('status',user.status==='active'?'locked':'active')+field('reason','Reason'),user.status==='active'?'Lock account':'Unlock account',user.status==='active')}</details>`:''}</td></tr>`).join('');
 return {name:'admin/users',view:{setup,filters:markup(filters),heading:tr('nav.users'),count:tr('number.value',{value:users.length}),caption:tr('copy.accountsEmailAddressesMasked'),columns:{select:tr('copy.select'),account:tr('nav.account'),status:tr('copy.status'),lastSeen:tr('users.filter.lastSeen'),roles:tr('nav.roles'),actions:tr('copy.actions')},rows:markup(rows),empty:text('No matching accounts. Try changing your filters.'),caveat:tr('users.filter.activityCaveat'),nextHref:input.next?nextPage(mount+'/users',query,input.next,userFilterKeys):null,nextLabel:tr('action.next'),bulk,exports}};
}
