import {escapeHtml} from '@jimhoyd/urlcode-ui';
import {hasPermission} from '@jimhoyd/urlcode-auth';
import type {AuthService,AuthPrincipal,PresentationContext} from '@jimhoyd/urlcode-auth';
export function dashboardSummary(stats:Awaited<ReturnType<AuthService['dashboard']>>,mount:string,principal:AuthPrincipal,presentation:PresentationContext):string {
 const text=(value:string)=>escapeHtml(presentation.textSource(value));
 const number=(value:number)=>escapeHtml(presentation.text('number.value',{value}));
 const items:[string,number,string,string][]=[['Accounts',stats.users,'/users','auth.users.read'],['Active accounts',stats.users-stats.locked-stats.pendingDeletion,'/users?status=active','auth.users.read'],['Locked accounts',stats.locked,'/users?status=locked','auth.users.read'],['Pending deletion',stats.pendingDeletion,'/users?status=pending-delete','auth.users.read'],['Sessions',stats.sessions,'/sessions','auth.sessions.manage'],['Waiting for approval',stats.waitlist,'/registrations','auth.users.manage']];
 const totals=`<div class="ui-metrics" role="group" aria-label="${escapeHtml(presentation.text('message.adminTotals',{users:stats.users,locked:stats.locked,pending:stats.pendingDeletion,sessions:stats.sessions,waitlist:stats.waitlist}))}">${items.filter(([, , ,permission])=>hasPermission(principal,permission)).map(([label,count,path])=>`<a class="ui-card ui-metric" href="${escapeHtml(mount+path)}"><span class="ui-muted">${text(label)}</span><strong>${number(count)}</strong><span aria-hidden="true">↗</span></a>`).join('')}</div>`;
 const days=stats.daily.slice(-30),peak=Math.max(1,...days.flatMap(day=>[day.signUps,day.signIns,day.failedSignIns]));
 const colors=['var(--chart-1)','var(--chart-2)','var(--chart-3)'];
 const lines=(['signUps','signIns','failedSignIns'] as const).map((key,index)=>`<polyline fill="none" stroke="${colors[index]}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"${index===2?' stroke-dasharray="5 4"':''} points="${days.map((day,i)=>`${64+i*526/Math.max(1,days.length-1)},${160-Math.round(Math.max(0,day[key])/peak*130)}`).join(' ')}"/>`).join('');
 const grid=[30,95,160].map(y=>`<line x1="64" y1="${y}" x2="590" y2="${y}" stroke="currentColor" opacity="0.1"/>`).join('');
 const labels=`<text x="54" y="34" text-anchor="end" font-size="14" fill="currentColor">${number(peak)}</text><text x="54" y="164" text-anchor="end" font-size="14" fill="currentColor">${number(0)}</text>${days.length?`<text x="64" y="184" font-size="14" fill="currentColor">${escapeHtml(days[0]!.day)} UTC</text><text x="590" y="184" text-anchor="end" font-size="14" fill="currentColor">${escapeHtml(days.at(-1)!.day)} UTC</text>`:''}`;
 return totals+`<section class="ui-card ui-chart" aria-labelledby="activity-heading"><div class="ui-section-heading"><div><h2 id="activity-heading">${text('Authentication activity')}</h2><p class="ui-muted">${escapeHtml(presentation.text('copy.authenticationActivityLast30UTCDays'))}</p></div><span class="ui-badge">UTC</span></div><svg viewBox="0 0 620 190" role="img" aria-labelledby="auth-chart-title auth-chart-description"><title id="auth-chart-title">${text('Authentication activity')}</title><desc id="auth-chart-description">${text('Thirty UTC days of sign-ups, sign-ins and failed sign-ins. Failed sign-ins use a dashed line. Exact values follow in the daily table.')}</desc>${grid}${lines}${labels}</svg><div class="ui-chart-legend"><span><i class="ui-chart-key ui-chart-key-blue" aria-hidden="true"></i>${escapeHtml(presentation.text('copy.signUps'))}</span><span><i class="ui-chart-key ui-chart-key-green" aria-hidden="true"></i>${escapeHtml(presentation.text('copy.signIns'))}</span><span><i class="ui-chart-key ui-chart-key-red" aria-hidden="true"></i>${escapeHtml(presentation.text('copy.failedSignIns'))}</span></div></section>`;
}
