import {escapeHtml} from '@jimhoyd/urlcode-ui';
import {csrfField,formField,hasPermission} from '@jimhoyd/urlcode-auth';
import type {AuthPrincipal,AuthUser,PresentationContext} from '@jimhoyd/urlcode-auth';
import {nextPage,observedLastSeen,userFilterFields,userFilterKeys} from './admin-reporting.ts';

/** Account workflows and authority stay here; URLCode UI supplies only generic visual primitives. */
export function userDirectory(input:{users:AuthUser[];next?:string;query:URLSearchParams;principal:AuthPrincipal;mount:string;csrf:string;presentation:PresentationContext;canSendSetup:boolean}):string {
 const {users,query,principal,mount,csrf,presentation}=input;
 const text=(source:string)=>escapeHtml(presentation.textSource(source));
 const tr=(key:string,values?:Record<string,string|number>)=>escapeHtml(presentation.text(key,values));
 const hidden=(name:string,value:string)=>`<input type="hidden" name="${name}" value="${escapeHtml(value)}">`;
 const field=(name:string,label:string,type='text')=>formField(name,presentation.textSource(label),type);
 const form=(path:string,fields:string,label:string)=>`<form class="ui-form-grid" method="post" action="${escapeHtml(mount+path)}">${csrfField(csrf)}${fields}<button type="submit">${text(label)}</button></form>`;
 const manage=hasPermission(principal,'auth.users.manage'),sessions=hasPermission(principal,'auth.sessions.manage'),select=manage||sessions;
 const setup=input.canSendSetup&&hasPermission(principal,'auth.users.create')?`<details class="ui-card"><summary>${text('Create account and send setup link')}</summary>${form('/users/create',field('email','Email address','email')+field('reason','Reason'),'Create account and send setup link')}</details>`:'';
 const filters=`<section class="ui-card"><form method="get" action="${escapeHtml(mount+'/users')}">${userFilterFields(query,source=>presentation.textSource(source))}<div class="ui-toolbar"><button type="submit">${tr('users.filter.apply')}</button><a href="${escapeHtml(mount+'/users'+(query.get('lang')?'?lang='+encodeURIComponent(query.get('lang')!):''))}">${text('Reset filters')}</a></div></form></section>`;
 const exported=hasPermission(principal,'auth.users.export')?`<details class="ui-card"><summary>${text('Export accounts')}</summary><div class="ui-form-grid">${form('/users/export-page',[...userFilterKeys,'after'].map(key=>hidden(key,query.get(key)||'')).join('')+field('reason','Reason')+`<p class="ui-muted">${tr('copy.exportThisFilteredPageOnlyAtMost50AccountsEmailAddressesStayMasked')}</p>`,'Export this page as CSV')}${form('/users/export-range',userFilterKeys.map(key=>hidden(key,query.get(key)||'')).join('')+field('reason','Reason')+`<p class="ui-muted">${text('Complete export: at most 5,000 accounts, 4 MiB and 5 seconds. Narrow filters if the limit is exceeded.')}</p>`,'Export all matching accounts as CSV')}</div></details>`:'';
 const bulk=select?`<details class="ui-card"><summary>${tr('copy.bulkAction')}</summary><form class="ui-form-grid" id="bulk-users" method="post" action="${escapeHtml(mount+'/users/bulk')}">${csrfField(csrf)}<label>${tr('copy.bulkAction')}<select name="action">${manage?`<option value="lock">${tr('copy.lock')}</option><option value="unlock">${tr('copy.unlock')}</option>`:''}${sessions?`<option value="revoke-sessions">${tr('action.revokeSessions')}</option>`:''}</select></label>${field('reason','Reason')}${field('confirmation','Type LOCK, UNLOCK or REVOKE-SESSIONS followed by a space and the selected count')}<p class="ui-muted">${tr('copy.selectAccountsInTheTableAllSelectedAccountsMustBePermittedOtherwiseNoneAreChanged')}</p><button type="submit">${tr('copy.applyBulkAction')}</button></form></details>`:'';
 const rows=users.map(user=>`<tr><td>${user.id!==principal.id&&user.status!=='pending-delete'&&select?`<input type="checkbox" form="bulk-users" name="selected.${escapeHtml(user.id)}" value="yes" aria-label="${tr('action.selectAccount',{account:user.email})}">`:''}</td><td><a href="${escapeHtml(mount+'/users/detail?id='+encodeURIComponent(user.id))}"><strong>${escapeHtml(user.email)}</strong></a><small class="ui-muted ui-account-id">${escapeHtml(user.id)}</small></td><td><span class="ui-badge" data-status="${escapeHtml(user.status)}">${text(user.status)}</span></td><td class="ui-muted">${observedLastSeen(user)?`<time datetime="${escapeHtml(observedLastSeen(user))}">${escapeHtml(observedLastSeen(user).replace('T',' ').replace('.000Z',' UTC'))}</time>`:'—'}</td><td>${user.roles.map(role=>`<span class="ui-badge">${escapeHtml(role)}</span>`).join(' ')}</td><td>${manage&&user.id!==principal.id&&user.status!=='pending-delete'?`<details><summary>${text(user.status==='active'?'Lock account':'Unlock account')}</summary>${form('/users/status',hidden('accountId',user.id)+hidden('status',user.status==='active'?'locked':'active')+field('reason','Reason'),user.status==='active'?'Lock account':'Unlock account')}</details>`:''}</td></tr>`).join('');
 const table=`<section class="ui-card"><div class="ui-section-heading"><h2>${tr('nav.users')}</h2><span class="ui-badge">${tr('number.value',{value:users.length})}</span></div><div class="ui-table-wrap" tabindex="0" role="region" aria-label="${tr('copy.accountsEmailAddressesMasked')}"><table class="ui-table"><caption>${tr('copy.accountsEmailAddressesMasked')}</caption><thead><tr><th scope="col">${tr('copy.select')}</th><th scope="col">${tr('nav.account')}</th><th scope="col">${tr('copy.status')}</th><th scope="col">${tr('users.filter.lastSeen')}</th><th scope="col">${tr('nav.roles')}</th><th scope="col">${tr('copy.actions')}</th></tr></thead><tbody>${rows||`<tr><td colspan="6" class="ui-empty">${text('No matching accounts. Try changing your filters.')}</td></tr>`}</tbody></table></div><p class="ui-muted">${tr('users.filter.activityCaveat')}</p>${input.next?`<div class="ui-toolbar"><a class="ui-button" href="${escapeHtml(nextPage(mount+'/users',query,input.next,userFilterKeys))}">${tr('action.next')}</a></div>`:''}</section>`;
 return setup+filters+table+bulk+exported;
}
