import {escapeHtml} from '@jimhoyd/urlcode-ui';
import {formField,csrfField,hasPermission} from '@jimhoyd/urlcode-auth';
import type {AuthService,AuthUser,AuthPrincipal,PresentationContext} from '@jimhoyd/urlcode-auth';
import {adminTime} from './admin-screens.ts';
export function accountDetail(input:{user:AuthUser;principal:AuthPrincipal;mount:string;csrf:string;presentation:PresentationContext;sessions?:Awaited<ReturnType<AuthService['listSessions']>>;activity?:Awaited<ReturnType<AuthService['listAudit']>>;notes?:Awaited<ReturnType<AuthService['listAudit']>>;operations:boolean;recovery?:boolean}):string {
 const {user,principal,mount,csrf,presentation,sessions,activity,notes}=input;
 const text=(source:string)=>escapeHtml(presentation.textSource(source)),value=escapeHtml;
 const url=(path:string)=>escapeHtml(mount+path),id=encodeURIComponent(user.id),field=(name:string,label:string)=>formField(name,presentation.textSource(label));
 const form=(path:string,fields:string,label:string,destructive=false)=>`<form class="ui-form-grid" method="post" action="${url(path)}">${csrfField(csrf)}<input type="hidden" name="accountId" value="${value(user.id)}">${fields}<div class="ui-actions"><button${destructive?' class="ui-button-destructive"':''} type="submit">${text(label)}</button></div></form>`;
 const sections=[['overview','Overview'],['methods','Sign-in methods'],['sessions','Sessions'],['recovery','Recovery'],['activity','Activity'],['data','Data']];
 const section=(key:string,title:string,body:string)=>`<section class="ui-card" id="detail-${key}" aria-labelledby="heading-${key}"><h2 id="heading-${key}">${text(title)}</h2>${body}</section>`;
 const empty=(message:string)=>`<p class="ui-empty">${text(message)}</p>`;
 const facts=[['Account ID',user.id],['Email',user.email],['Status',user.status],['Email verified',user.emailVerified?'Yes':'No'],['Roles',user.roles.join(', ')],['Created',new Date(user.created).toISOString()],['Display name',user.profile?.displayName??'—'],['Language',user.profile?.locale??'—']];
 const operations=input.operations&&user.id!==principal.id?`<a class="ui-button-secondary" href="${url('/account-operations?accountId='+id)}">${text('Account administration')}</a>`:'';
 const overview=`<dl class="ui-definition-grid">${facts.map(([name,content])=>`<dt>${text(name!)}</dt><dd>${value(content!)}</dd>`).join('')}</dl>`+(hasPermission(principal,'auth.users.reveal')?`<details><summary>${text('Reveal email address')}</summary>${form('/users/reveal',field('reason','Reason'),'Reveal email address')}</details>`:'')+(notes?`<h3>${text('Administrator notes')}</h3>${notes.events.length?`<ul class="ui-list">${notes.events.map(note=>`<li><p>${value(note.reason)}</p><small class="ui-muted">${value(note.actor)} · ${adminTime(note.created)}</small></li>`).join('')}</ul>`:empty('No administrator notes yet.')}`:'')+(hasPermission(principal,'auth.users.manage')?`<details><summary>${text('Save administrator note')}</summary><p class="ui-muted">${text('Notes are recorded in the audit trail. Do not include credentials or recovery secrets.')}</p>${form('/users/note',field('reason','Administrator note'),'Save administrator note')}</details>`:'');
 const sessionBody=sessions?(sessions.length?`<ul class="ui-list">${sessions.map(session=>`<li><strong>${value(session.deviceLabel??presentation.textSource('Unknown device'))}</strong><dl class="ui-definition-grid"><dt>${text('Created')}</dt><dd>${adminTime(session.created)}</dd><dt>${text('Expires')}</dt><dd>${adminTime(session.expires)}</dd></dl><details><summary>${text('Revoke this session')}</summary>${form('/sessions/revoke-one',`<input type="hidden" name="sessionId" value="${value(session.id)}">`+field('reason','Reason'),'Revoke this session',true)}</details></li>`).join('')}</ul><details class="ui-danger-zone"><summary>${text('Revoke all sessions')}</summary><p class="ui-muted">${text('The user can sign in again unless their account is locked.')}</p>${form('/sessions/revoke',field('reason','Reason'),'Revoke all sessions',true)}</details>`:empty('No active sessions match these filters.')):empty('Session management permission is required.');
 const activityBody=activity?(activity.events.length?`<ul class="ui-list">${activity.events.map(event=>`<li><code>${value(event.action)}</code><p class="ui-muted">${adminTime(event.created)} · ${value(event.actor)}</p></li>`).join('')}</ul>`:empty('No account activity recorded.'))+`<a class="ui-button-secondary" href="${url('/audit?subject='+id)}">${text('View account audit')}</a>`:empty('Audit permission is required.');
 const recoveryLinks=hasPermission(principal,'auth.cases.read')?`<div class="ui-actions">${input.recovery?`<a class="ui-button-secondary" href="${url('/recovery-cases')}">${text('Manual account recovery')}</a>`:''}<a class="ui-button-secondary" href="${url('/cases')}">${text('Security cases')}</a></div>`:'';
 return `<div class="ui-toolbar"><a href="${url('/users')}">${text('Back to users')}</a><span class="ui-badge">${value(user.status)}</span></div><nav class="ui-toolbar" aria-label="${text('Account sections')}">${sections.map(([key,label])=>`<a href="#detail-${key}">${text(label!)}</a>`).join('')}</nav>`+section('overview','Overview',overview)+section('methods','Sign-in methods',`<dl class="ui-definition-grid"><dt>${text('Authenticator enabled')}</dt><dd>${text(user.totpEnabled?'Yes':'No')}</dd><dt>${text('Passkey second factor enabled')}</dt><dd>${text(user.passkeyMfaEnabled?'Yes':'No')}</dd></dl>`+operations)+section('sessions','Sessions',sessionBody)+section('recovery','Recovery',`<p class="ui-muted">${text('Recovery contacts are not supported in this release. Manual evidence requires independent operator assessment.')}</p>`+recoveryLinks)+section('activity','Activity',activityBody)+section('data','Data',`<h3>${text('Consent record')}</h3>${user.profile?.terms?`<pre>${value(JSON.stringify(user.profile.terms,null,2))}</pre>`:empty('No consent record is stored for this account.')}`+(hasPermission(principal,'auth.users.export')?`<details><summary>${text('Export account data')}</summary>${form('/users/export',field('reason','Reason'),'Export account data')}</details>`:'')+operations);
}
