import {escapeHtml,formField,csrfField,hasPermission} from '@jimhoyd/urlcode-auth';
import type {AuthService,AuthUser,AuthPrincipal,PresentationContext} from '@jimhoyd/urlcode-auth';
export function accountDetail(input:{user:AuthUser;principal:AuthPrincipal;mount:string;csrf:string;presentation:PresentationContext;sessions?:Awaited<ReturnType<AuthService['listSessions']>>;activity?:Awaited<ReturnType<AuthService['listAudit']>>;notes?:Awaited<ReturnType<AuthService['listAudit']>>;operations:boolean}):string {
 const {user,principal,mount,csrf,presentation,sessions,activity,notes}=input;
 const text=(source:string)=>escapeHtml(presentation.textSource(source)), value=escapeHtml;
 const url=(path:string)=>escapeHtml(mount+path),id=encodeURIComponent(user.id),field=(name:string,label:string)=>formField(name,presentation.textSource(label));
 const form=(path:string,fields:string,label:string)=>`<form method="post" action="${url(path)}">${csrfField(csrf)}<input type="hidden" name="accountId" value="${value(user.id)}">${fields}<button>${text(label)}</button></form>`;
 const sections=[['overview','Overview'],['methods','Sign-in methods'],['sessions','Sessions'],['recovery','Recovery'],['activity','Activity'],['data','Data']];
 const section=(key:string,title:string,body:string)=>`<section id="detail-${key}" aria-labelledby="heading-${key}"><h2 id="heading-${key}">${text(title)}</h2>${body}</section>`;
 const facts=[['Account ID',user.id],['Email',user.email],['Status',user.status],['Email verified',user.emailVerified?'Yes':'No'],['Roles',user.roles.join(', ')],['Created',new Date(user.created).toISOString()],['Display name',user.profile?.displayName??''],['Language',user.profile?.locale??'']];
 const operations=input.operations&&user.id!==principal.id?`<p><a href="${url('/account-operations?accountId='+id)}">${text('Account administration')}</a></p>`:'';
 const overview=`<dl>${facts.map(([name,content])=>`<dt>${text(name!)}</dt><dd>${value(content!)}</dd>`).join('')}</dl>`+(hasPermission(principal,'auth.users.reveal')?form('/users/reveal',field('reason','Reason'),'Reveal email address'):'')+(notes?`<h3>${text('Administrator notes')}</h3><ul>${notes.events.map(note=>`<li>${value(note.reason)} — ${value(note.actor)} · ${value(new Date(note.created).toISOString())}</li>`).join('')}</ul>`:'')+(hasPermission(principal,'auth.users.manage')?form('/users/note',field('reason','Administrator note'),'Save administrator note'):'');
 const sessionBody=sessions?`<ul>${sessions.map(session=>`<li>${value(session.deviceLabel??'Unknown device')} · ${value(new Date(session.created).toISOString())} — ${value(new Date(session.expires).toISOString())}${form('/sessions/revoke-one',`<input type="hidden" name="sessionId" value="${value(session.id)}">`+field('reason','Reason'),'Revoke this session')}</li>`).join('')}</ul>`+form('/sessions/revoke',field('reason','Reason'),'Revoke all sessions'):`<p>${text('Session management permission is required.')}</p>`;
 const activityBody=activity?`<ul>${activity.events.map(event=>`<li>${value(event.action)} — ${value(new Date(event.created).toISOString())} · ${value(event.actor)}</li>`).join('')}</ul><a href="${url('/audit?subject='+id)}">${text('View account audit')}</a>`:`<p>${text('Audit permission is required.')}</p>`;
 return `<nav aria-label="${text('Account sections')}">${sections.map(([key,label])=>`<a href="#detail-${key}">${text(label!)}</a>`).join(' · ')}</nav>`+section('overview','Overview',overview)+section('methods','Sign-in methods',`<p>${text('Authenticator enabled')}: ${text(user.totpEnabled?'Yes':'No')}. ${text('Passkey second factor enabled')}: ${text(user.passkeyMfaEnabled?'Yes':'No')}.</p>`+operations)+section('sessions','Sessions',sessionBody)+section('recovery','Recovery',`<p>${text('Recovery contacts are not supported in this release. Manual evidence requires independent operator assessment.')}</p>`+(hasPermission(principal,'auth.cases.read')?`<a href="${url('/recovery-cases')}">${text('Manual account recovery')}</a> · <a href="${url('/cases')}">${text('Security cases')}</a>`:''))+section('activity','Activity',activityBody)+section('data','Data',`<h3>${text('Consent record')}</h3><pre>${value(JSON.stringify(user.profile?.terms??{},null,2))}</pre>`+(hasPermission(principal,'auth.users.export')?form('/users/export',field('reason','Reason'),'Export account data'):'')+operations);
}
