import {escapeHtml,field,icon} from '@jimhoyd/urlcode-ui';
import {csrfField,hasPermission} from '@jimhoyd/urlcode-auth';
import type {AuthService,AuthPrincipal,PresentationContext} from '@jimhoyd/urlcode-auth';
import type {AdminHealthSnapshot} from './admin-health.ts';
import {maskEmail,nextPage} from './admin-reporting.ts';
interface Screen {mount:string;csrf:string;principal:AuthPrincipal;presentation:PresentationContext;query:URLSearchParams}
function tools(input:Screen){
 const text=(source:string)=>escapeHtml(input.presentation.textSource(source));
 const tr=(key:string)=>escapeHtml(input.presentation.text(key));
 const url=(path:string)=>escapeHtml(input.mount+path);
 const filter=(name:string,label:string,required=false)=>field({name,label:input.presentation.textSource(label),required,value:input.query.get(name)||''});
 const form=(path:string,body:string,label:string,destructive=false)=>`<form class="ui-form-grid" method="post" action="${url(path)}">${csrfField(input.csrf)}${body}<div class="ui-actions"><button${destructive?' class="ui-button-destructive"':''} type="submit">${text(label)}</button></div></form>`;
 const hidden=(name:string,value:string)=>`<input type="hidden" name="${name}" value="${escapeHtml(value)}">`;
 const reason=()=>field({name:'reason',label:input.presentation.textSource('Reason'),description:input.presentation.textSource('Sensitive actions require a recent sign-in and a reason.')});
 const table=(caption:string,headings:string[],rows:string)=>`<div class="ui-table-wrap" tabindex="0" role="region" aria-label="${caption}"><table class="ui-table"><caption>${caption}</caption><thead><tr>${headings.map(heading=>`<th scope="col">${heading}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;
 const empty=(message:string)=>`<p class="ui-empty">${text(message)}</p>`;
 return {text,tr,url,filter,form,hidden,reason,table,empty};
}
export function adminTime(value:number|string):string {
 const date=new Date(value);return `<time datetime="${escapeHtml(date.toISOString())}">${escapeHtml(date.toISOString().slice(0,16).replace('T',' '))} UTC</time>`;
}
export function rolesScreen(input:Screen&{roles:ReturnType<AuthService['getRoles']>}):string {
 const {text,tr,url,form,reason,table}=tools(input);
 const rows=Object.entries(input.roles).map(([name,grants])=>`<tr><th scope="row">${escapeHtml(name)}</th><td>${grants.length?grants.map(grant=>`<code>${escapeHtml(grant)}</code>`).join('<br>'):`<span class="ui-muted">${text('No additional permissions')}</span>`}</td><td>${hasPermission(input.principal,'auth.users.read')?`<a href="${url('/users?role='+encodeURIComponent(name))}">${tr('nav.users')}</a>`:''}</td></tr>`).join('');
 return `<section class="ui-card"><p>${text('Review the permissions each role grants. Assign reviewed roles to an account below.')}</p><p class="ui-muted">${tr('copy.roleDefinitionsAreReadOnlyHere')}</p>${table(tr('nav.roles'),[text('Role name'),text('Permissions'),text('Accounts')],rows)}</section>`+(hasPermission(input.principal,'auth.users.manage')?`<section class="ui-card"><h2>${text('Assign roles')}</h2>${form('/users/roles',field({name:'accountId',label:input.presentation.textSource('Account ID')})+field({name:'roles',label:input.presentation.textSource('Role names separated by commas')})+reason(),'Assign roles')}</section>`:'');
}
export function sessionsScreen(input:Screen&{result:Awaited<ReturnType<AuthService['listAllSessions']>>}):string {
 const {text,tr,url,form,reason,hidden,filter,table,empty}=tools(input);
 const rows=input.result.sessions.map(session=>`<tr><td>${hasPermission(input.principal,'auth.users.read')?`<a href="${url('/users/detail?id='+encodeURIComponent(session.accountId))}">${escapeHtml(maskEmail(session.email))}</a>`:escapeHtml(maskEmail(session.email))}<small class="ui-muted ui-account-id">${escapeHtml(session.accountId)}</small></td><td>${escapeHtml(session.deviceLabel||input.presentation.textSource('Unknown device'))}</td><td>${adminTime(session.created)}</td><td>${adminTime(session.expires)}</td><td><details><summary>${text('Revoke this session')}</summary><p class="ui-muted">${text('The user can sign in again unless their account is locked.')}</p>${form('/sessions/revoke-one',hidden('sessionId',session.id)+reason(),'Revoke this session',true)}</details></td></tr>`).join('');
 const accountId=input.query.get('accountId');
 return `<section class="ui-card"><h2>${text('Filter sessions')}</h2><p class="ui-muted">${text('Review active sessions. Revoking a session signs that device out.')}</p><form class="ui-form-grid" method="get" action="${url('/sessions')}">${filter('accountId','Account ID')}${filter('device','Device')}${filter('createdFrom','Created from UTC')}${filter('createdTo','Created to UTC')}<div class="ui-actions"><button type="submit">${tr('action.findSessions')}</button><a class="ui-button-secondary" href="${url('/sessions')}">${text('Reset filters')}</a></div></form></section><section class="ui-card"><p class="ui-muted">${escapeHtml(input.presentation.text('message.sessionsOnPage',{count:input.result.sessions.length}))}</p>${rows?table(tr('nav.sessions'),[text('Account'),text('Device'),text('Created'),text('Expires'),text('Actions')],rows):empty('No active sessions match these filters.')}${input.result.next?`<p><a class="ui-button-secondary" href="${escapeHtml(nextPage(input.mount+'/sessions',input.query,input.result.next,['accountId','device','createdFrom','createdTo']))}">${tr('action.next')}</a></p>`:''}</section>`+(accountId&&input.result.sessions.length?`<details class="ui-card ui-danger-zone"><summary>${text('Revoke all sessions')}</summary><p class="ui-muted">${text('The user can sign in again unless their account is locked.')}</p>${form('/sessions/revoke',hidden('accountId',accountId)+reason(),'Revoke all sessions',true)}</details>`:'');
}
export function auditScreen(input:Screen&{result:Awaited<ReturnType<AuthService['listAudit']>>}):string {
 const {text,tr,url,filter,hidden,table,empty}=tools(input);
 const filters=()=>filter('actor','Actor account ID')+filter('subject','Subject account ID')+filter('action','Event action')+filter('from','From UTC (YYYY-MM-DDTHH:mmZ)')+filter('to','To UTC (YYYY-MM-DDTHH:mmZ)');
 const rows=input.result.events.map(event=>`<tr><td>${adminTime(event.created)}</td><td><code>${escapeHtml(event.action)}</code></td><td>${escapeHtml(event.actor)}</td><td>${escapeHtml(event.subject)}</td></tr>`).join('');
 return `<section class="ui-card"><h2>${text('Filter audit events')}</h2><p class="ui-muted">${text('Review recorded security events. Use filters to narrow the time range or account.')}</p><form class="ui-form-grid" method="get" action="${url('/audit')}">${filters()}<div class="ui-actions"><button type="submit">${tr('copy.filterAudit')}</button><a class="ui-button-secondary" href="${url('/audit')}">${text('Reset filters')}</a></div></form></section><section class="ui-card">${rows?table(tr('copy.recentSecurityEvents'),[tr('copy.time'),tr('copy.action'),tr('copy.actor'),tr('copy.subject')],rows):empty('No audit events match these filters.')}${input.result.next?`<p><a class="ui-button-secondary" href="${escapeHtml(nextPage(input.mount+'/audit',input.query,input.result.next,['actor','subject','action','from','to']))}">${tr('action.next')}</a></p>`:''}</section>`+(hasPermission(input.principal,'auth.audit.export')?`<details class="ui-card"><summary>${icon('download')}<span>${text('Export audit events')}</span></summary><form class="ui-form-grid" method="get" action="${url('/audit/export')}">${['actor','subject','action'].map(key=>hidden(key,input.query.get(key)||'')).join('')}${filter('from','From UTC (YYYY-MM-DDTHH:mmZ)',true)}${filter('to','To UTC (YYYY-MM-DDTHH:mmZ)',true)}<div class="ui-actions"><button class="ui-button-secondary" type="submit">${tr('action.exportAudit')}</button></div></form></details>`:'');
}
export function healthScreen(input:Screen&{health:AdminHealthSnapshot|null;configured:boolean}):string {
 const {text,tr,table,empty}=tools(input),health=input.health;
 if(!health)return `<section class="ui-card">${empty(input.configured?input.presentation.text('health.unavailableStatus'):input.presentation.text('health.unavailable'))}</section>`;
 const status=(value:string)=>`<span class="ui-badge" data-status="${escapeHtml(value)}">${tr('health.'+(value==='unavailable'?'unavailableStatus':value))}</span>`;
 const components:[[string,string],...[string,string][]]=[[tr('health.runtime'),health.runtime.status],[tr('health.readiness'),health.runtime.readiness],[tr('health.sender'),health.sender],...health.providers.map(provider=>[tr('health.provider')+': '+escapeHtml(provider.id),provider.status] as [string,string])];
 const messages={'sender-failed':'Notification sender reported a failure.','provider-expiring':'A provider credential is approaching expiry.','presentation-outdated':'The configured presentation needs an update.','translation-incomplete':'Some translations are incomplete.'};
 return `<section class="ui-card"><p class="ui-muted">${text('Reported observations from this host and its configured integrations.')}</p><dl class="ui-definition-grid"><dt>${tr('health.updated')}</dt><dd>${adminTime(health.checkedAt)}</dd><dt>${tr('health.version')}</dt><dd><code>${escapeHtml(health.runtime.version)}</code></dd><dt>${tr('health.routes')}</dt><dd>${escapeHtml(input.presentation.text('number.value',{value:health.runtime.routes}))}</dd></dl></section><section class="ui-card">${table(tr('health.component'),[tr('health.component'),tr('health.status')],components.map(([label,value])=>`<tr><th scope="row">${label}</th><td>${status(value)}</td></tr>`).join(''))}</section><section class="ui-card"><h2>${tr('health.alerts')}</h2>${health.alerts.length?`<ul class="ui-list">${health.alerts.map(alert=>`<li>${text(messages[alert])}</li>`).join('')}</ul>`:empty('No alerts reported.')}</section>`;
}
export function casesScreen(input:Screen&{result:Awaited<ReturnType<AuthService['listCases']>>}):string {
 const {text,tr,url,form,hidden,reason,empty}=tools(input),manage=hasPermission(input.principal,'auth.cases.manage');
 const items=input.result.cases.map(item=>`<li class="ui-card"><div class="ui-section-heading"><h2><code>${escapeHtml(item.action)}</code></h2><span class="ui-badge">${escapeHtml(item.status)}</span></div><dl class="ui-definition-grid"><dt>${text('Account ID')}</dt><dd>${escapeHtml(item.accountId)}</dd><dt>${text('Reason')}</dt><dd>${escapeHtml(item.reason)}</dd></dl>${item.notes?.length?`<ul class="ui-list">${item.notes.map(note=>`<li><p>${escapeHtml(note.note)}</p><small class="ui-muted">${escapeHtml(note.actorId)}</small></li>`).join('')}</ul>`:''}${manage?`<details><summary>${text('Add note')}</summary>${form('/cases/note',hidden('caseId',item.id)+reason(),'Add note')}</details>`:''}${manage&&item.status==='pending'?`<details><summary>${text('Close without applying')}</summary>${form('/cases/close',hidden('caseId',item.id)+reason(),'Close without applying')}</details>`:''}${manage&&item.status==='pending'&&item.makerId!==input.principal.id?`<details class="ui-danger-zone"><summary>${text('Approve and apply')}</summary>${form('/cases/approve',hidden('caseId',item.id)+reason(),'Approve and apply',true)}</details>`:''}</li>`).join('');
 const actions=['reset-factors','lock','unlock','roles'];
 return (items?`<ul class="ui-list">${items}</ul>`:`<section class="ui-card">${empty('No support cases to review.')}</section>`)+(manage?`<details class="ui-card"><summary>${text('Create a support case')}</summary>${form('/cases/create',field({name:'accountId',label:input.presentation.textSource('Account ID')})+`<label>${text('Action: reset-factors, lock, unlock or roles')}<select name="action">${actions.map(action=>`<option value="${action}">${escapeHtml(action)}</option>`).join('')}</select></label>`+field({name:'roles',label:input.presentation.textSource('Roles (for roles action)'),required:false})+reason(),'Create case for a second administrator')}</details>`:'')+(input.result.next?`<p><a class="ui-button-secondary" href="${url('/cases?after='+encodeURIComponent(input.result.next))}">${tr('action.next')}</a></p>`:'');
}
export function registrationsScreen(input:Screen&{result:Awaited<ReturnType<AuthService['listRegistrationRequests']>>;canInvite:boolean}):string {
 const {text,tr,url,form,hidden,reason,empty}=tools(input);
 const items=input.result.requests.map(item=>`<li class="ui-card"><h2>${escapeHtml(maskEmail(item.email))}</h2>${form('/registrations/approve',hidden('requestId',item.id)+reason(),'Approve account')}</li>`).join('');
 return (items?`<ul class="ui-list">${items}</ul>`:`<section class="ui-card">${empty('No registration requests are waiting for approval.')}</section>`)+(input.result.next?`<p><a class="ui-button-secondary" href="${url('/registrations?after='+encodeURIComponent(input.result.next))}">${tr('action.next')}</a></p>`:'')+(input.canInvite&&hasPermission(input.principal,'auth.users.create')?`<section class="ui-card"><h2>${text('Send invitation')}</h2>${form('/invitations',field({name:'email',label:input.presentation.textSource('Email address'),type:'email'})+reason(),'Send invitation')}</section>`:'');
}
